namespace :degrees do
  # Candidate names per difficulty tier. Easy = household names with huge filmographies, hard = famous but
  # with narrower or older careers. Names are resolved to TMDb ids by `degrees:seed`.
  CANDIDATES = {
    "easy" => [ "Tom Hanks", "Meryl Streep", "Robert De Niro", "Samuel L. Jackson", "Brad Pitt", "Leonardo DiCaprio",
                "Julia Roberts", "Morgan Freeman", "Denzel Washington", "Sandra Bullock", "Will Smith",
                "Scarlett Johansson", "Matt Damon", "Nicole Kidman", "Harrison Ford", "Jennifer Lawrence" ],
    "medium" => [ "Kevin Bacon", "Cate Blanchett", "Bill Murray", "Susan Sarandon", "Willem Dafoe", "Tilda Swinton",
                  "Jeff Goldblum", "Viola Davis", "Steve Buscemi", "Laura Dern", "John Goodman", "Frances McDormand",
                  "Christopher Walken", "Helen Mirren", "Jason Bateman" ],
    "hard" => [ "Anthony Hopkins", "Gene Hackman", "Judi Dench", "Michael Caine", "Sigourney Weaver", "Jack Nicholson",
                "Catherine Deneuve", "Max von Sydow", "Donald Sutherland", "Christopher Lee", "Maggie Smith",
                "Ian McKellen", "Dustin Hoffman" ]
  }.freeze
  MIN_CREDITS = 30
  OUTPUT = Rails.root.join("config/degrees_targets.yml")

  desc "Resolve candidate names to TMDb ids, drop thin filmographies, write config/degrees_targets.yml"
  task seed: :environment do
    tmdb = TmdbClient.new
    filter = CreditFilter.new(skip_self: true, skip_voice: true)
    targets = Hash.new { |h, k| h[k] = [] }

    CANDIDATES.each do |tier, names|
      names.each do |name|
        match = tmdb.search_person(name).first
        unless match
          puts "#{tier.ljust(6)} #{name}: NO MATCH"
          next
        end
        credits = filter.call(tmdb.person_credits(match.id)).uniq { |c| CreditFilter.title_key(c.media_type, c.id) }
        verdict = credits.size >= MIN_CREDITS ? "ok  " : "DROP"
        puts "#{tier.ljust(6)} #{verdict} #{name} -> #{match.name} (#{match.id}) #{credits.size} credits; " \
             "known for #{match.known_for.join(', ')}"
        targets[tier] << { "name" => match.name, "id" => match.id } if credits.size >= MIN_CREDITS
      end
    end

    File.write(OUTPUT, "# Six Degrees targets, generated by `bin/rails degrees:seed` (edit CANDIDATES in lib/tasks/degrees.rake).\n" \
                       "# name + TMDb person id; everyone has >= #{MIN_CREDITS} credits surviving the default rules.\n" +
                       targets.to_h.to_yaml)
    puts "Wrote #{targets.values.sum(&:size)} targets to #{OUTPUT}"
  end
end
